//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace productlistoriginT.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal localization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("productlistoriginT.Properties.localization", typeof(localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   GİRİŞ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S001 {
            get {
                return ResourceManager.GetString("S001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TÜRKÇE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S002 {
            get {
                return ResourceManager.GetString("S002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S003 {
            get {
                return ResourceManager.GetString("S003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S004 {
            get {
                return ResourceManager.GetString("S004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KULLANICI: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S005 {
            get {
                return ResourceManager.GetString("S005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÜRÜN ID benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S006 {
            get {
                return ResourceManager.GetString("S006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADET benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S007 {
            get {
                return ResourceManager.GetString("S007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EKLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S008 {
            get {
                return ResourceManager.GetString("S008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SAT benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S009 {
            get {
                return ResourceManager.GetString("S009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÜRÜN BİLGİSİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S010 {
            get {
                return ResourceManager.GetString("S010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İSTATİSTİK benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S011 {
            get {
                return ResourceManager.GetString("S011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MÜŞTERİ BİLGİSİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S012 {
            get {
                return ResourceManager.GetString("S012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÜRÜN KONUM benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S013 {
            get {
                return ResourceManager.GetString("S013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ara benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S014 {
            get {
                return ResourceManager.GetString("S014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YENİ KULLANICI EKLE/SİL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S015 {
            get {
                return ResourceManager.GetString("S015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KULLANICI ADI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S016 {
            get {
                return ResourceManager.GetString("S016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ŞİFRE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S017 {
            get {
                return ResourceManager.GetString("S017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KULLANICI NO benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S018 {
            get {
                return ResourceManager.GetString("S018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SİL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S019 {
            get {
                return ResourceManager.GetString("S019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KULLANICI GEÇMİŞİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S020 {
            get {
                return ResourceManager.GetString("S020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GEÇMİŞİ TEMİZLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S021 {
            get {
                return ResourceManager.GetString("S021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MÜŞTERİ TC benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S022 {
            get {
                return ResourceManager.GetString("S022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SATIŞ TÜRÜ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S023 {
            get {
                return ResourceManager.GetString("S023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Borç benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S024 {
            get {
                return ResourceManager.GetString("S024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   müşteri borçları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S025 {
            get {
                return ResourceManager.GetString("S025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   müşteri alımları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S026 {
            get {
                return ResourceManager.GetString("S026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MİKTAR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S027 {
            get {
                return ResourceManager.GetString("S027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BORÇ TAHSİL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S028 {
            get {
                return ResourceManager.GetString("S028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EN POPÜLER ÜRÜNLER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S029 {
            get {
                return ResourceManager.GetString("S029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÜRÜN STOK DURUMU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S030 {
            get {
                return ResourceManager.GetString("S030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÇOK KAZANDIRAN MÜŞTERİLER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S031 {
            get {
                return ResourceManager.GetString("S031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TOPLAM KAZANÇ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S032 {
            get {
                return ResourceManager.GetString("S032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STOK GİDERİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S033 {
            get {
                return ResourceManager.GetString("S033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STOK DEĞERİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S034 {
            get {
                return ResourceManager.GetString("S034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AD benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S035 {
            get {
                return ResourceManager.GetString("S035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SOYAD benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S036 {
            get {
                return ResourceManager.GetString("S036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADRES benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S037 {
            get {
                return ResourceManager.GetString("S037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TELEFON benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S038 {
            get {
                return ResourceManager.GetString("S038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GÜNCELLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S039 {
            get {
                return ResourceManager.GetString("S039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TC ARA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S040 {
            get {
                return ResourceManager.GetString("S040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YENİ KULLANICI İŞLEMLERİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S041 {
            get {
                return ResourceManager.GetString("S041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ANA SAYFA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S042 {
            get {
                return ResourceManager.GetString("S042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HAREKET GEÇMİŞİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S043 {
            get {
                return ResourceManager.GetString("S043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KULLANICI GİRİŞ GEÇMİŞİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S044 {
            get {
                return ResourceManager.GetString("S044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÜRÜN ADI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S045 {
            get {
                return ResourceManager.GetString("S045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KATEGORİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S046 {
            get {
                return ResourceManager.GetString("S046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MARKA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S047 {
            get {
                return ResourceManager.GetString("S047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KALİTE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S048 {
            get {
                return ResourceManager.GetString("S048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AKSESUAR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S049 {
            get {
                return ResourceManager.GetString("S049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÜRETİM YERİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S050 {
            get {
                return ResourceManager.GetString("S050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FİYATI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S051 {
            get {
                return ResourceManager.GetString("S051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DEPO NO benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S052 {
            get {
                return ResourceManager.GetString("S052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MALİYETİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S053 {
            get {
                return ResourceManager.GetString("S053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÜRÜN ADET benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S054 {
            get {
                return ResourceManager.GetString("S054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STOKTAN ÜRÜN SİL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S055 {
            get {
                return ResourceManager.GetString("S055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID ARA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S056 {
            get {
                return ResourceManager.GetString("S056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MÜŞTERİ İŞLEMLERİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S057 {
            get {
                return ResourceManager.GetString("S057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÜRÜN İŞLEMLERİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S058 {
            get {
                return ResourceManager.GetString("S058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADMİN EKRANI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S059 {
            get {
                return ResourceManager.GetString("S059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RAPORLA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S060 {
            get {
                return ResourceManager.GetString("S060", resourceCulture);
            }
        }
    }
}
